[package]
name = "day25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
petgraph = "0.6.4"

[[bin]]
name = "p2"
path = "p2.rs"

[[bin]]
name = "p1"
path = "p1.rs"

