[package]
name = "day24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "0.12.1"


[[bin]]
name = "day24_p2"
path = "p2.rs"

[[bin]]
name = "day24_p1"
path = "p1.rs"
